### ISSUE TITLE
Add Caddy as a Deployment

### ISSUE THREAD

**Issue by mishraomp** [bcgov/nr-caddy-proxy#4]

**Comment by mishraomp** [comment]
@DerekRoberts would you be able to help and add the vars and secrets for this to go to our Platform Security Tools Demonstration namespace `32d13a`

**Comment by DerekRoberts** [comment]
@mishraomp Not a problem!  Likely early next week, at this rate.

**Comment by DerekRoberts** [comment]
Being rolled into Emerald work, later on.  Closing.
